import React, { useState } from "react";

import styles from "../smm/faq.module.scss";

export default function Faq() {
  const [active, setActive] = useState(0);
  return (
    <>
      <section className={styles.faq}>
        <div className={styles.container}>
          <h2>Frequently Asked Questions</h2>
            <h3>Results</h3>
          <div className={styles.faqContainer}>
            <div
              className={styles.question}
              onClick={() => setActive(active === 1 ? 0 : 1)}
            >
              <p>What type of results can I expect?</p>
              <img className={active === 1 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 1 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              The most important performance metrics we evaluate are website
              traffic and conversions. We will see how much traffic your website
              receives, and how many people actually convert.
            </p>
          </div>
          <div className={styles.faqContainer}>
            <div
              className={styles.question}
              onClick={() => setActive(active === 2 ? 0 : 2)}
            >
              <p>How much traffic can I expect?</p>
              <img className={active === 2 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 2 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              The amount of traffic generated monthly for you will depend
              <ul>
                <li>On the effectiveness of your campaign and</li>
                <li>Your advertising budget.</li>
              </ul>
              The more the budget in the house, the greater results we can
              generate for you.
            </p>
          </div>

          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 3 ? 0 : 3)}
          >
            <div className={styles.question}>
              <p>How many conversions can I expect?</p>
              <img className={active === 3 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 3 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              Conversion rates will also vary. We will be able to measure how
              many conversions are generated by our ads. We will then use this
              information to make improvements on them. Based on this, we
              anticipate your conversion rate to rise over time.
            </p>
            <p>
              {" "}
              We must remember, however, that there are external factors that
              influence conversions that we cannot control. For example, the
              competition you are in, the price, the product quality, and the
              website destination.
            </p>
          </div>
          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 4 ? 0 : 4)}
          >
            <div className={styles.question}>
              <p>
                {" "}
                How much do I need to spend to advertise on social media
                platforms?
              </p>
              <img className={active === 4 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 4 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              Social media advertising requires you to spend money, but there
              are different types of ad campaigns you can run. Some campaigns
              follow the pay-per-click model, similar to Google Ads and Bing
              Ads, while others focus on impressions. However, the exact amount
              you will need for each campaign will depend on several variables.
            </p>
            <p>
              It is important for our clients to consider what kind of customer
              they are looking to acquire. Once you understand this, identify
              the maximum you are willing to spend on an individual customer.
              Based on our experience, we believe we can help you acquire people
              at a profitable rate.
            </p>
          </div>
          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 5 ? 0 : 5)}
          >
            <div className={styles.question}>
              <p>How long are the contracts?</p>
              <img className={active === 5 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 5 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              We offer initial contract terms of 3 months. After the initial
              contract term is completed, your account will continue running
              month-to-month. Cancellation is guaranteed for 30 days. After 30
              days, we will terminate all services and return any information we
              have back to you.
            </p>
          </div>
          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 6 ? 0 : 6)}
          >
            <div className={styles.question}>
              <p>How long does it take to get started?</p>
              <img className={active === 6 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 6 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              If you are ready to begin, please contact us. One of our sales
              consultants will assist you in identifying the right plan of
              action for your campaign. Upon your approval, we will send you a
              contract and start your campaign immediately.
            </p>
          </div>
          <h3>Service &amp; Working Together</h3>
          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 7 ? 0 : 7)}
          >
            <div className={styles.question}>
              <p>Who will be working on my account?</p>
              <img className={active === 7 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 7 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              A dedicated account manager will be assigned to your company. This
              person is knowledgeable about social media marketing and is likely
              to have experience working with clients similar to yours. This
              person will be your point of contact. All deliverables are
              reviewed internally before they are sent to you. This ensures that
              you receive high-quality work and resolves challenging situations.
            </p>
          </div>
          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 8 ? 0 : 8)}
          >
            <div className={styles.question}>
              <p>How will you learn my business?</p>
              <img className={active === 8 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 8 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              To learn about your business we will send you a questionnaire.
              Following completion, a call will be scheduled to discuss the
              questionnaire for validation purposes. Also, we may need to ask
              you some additional questions about your business. Following the
              call, we will conduct further research and design a strategy
              specific to your business.
            </p>
          </div>
          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 9 ? 0 : 9)}
          >
            <div className={styles.question}>
              <p>How will you create ads that fit my business?</p>
              <img className={active === 9 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 9 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              The questionnaire helps us learn more about your ad preferences. A
              strategy that we develop for you will include the advertising
              approach that will be used on your business.The advertisement will
              be developed in an ad calendar based on your approval, and you
              will have the opportunity to review the advertisement before it is
              published
            </p>
          </div>
          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 10 ? 0 : 10)}
          >
            <div className={styles.question}>
              <p>Do I have to provide you with content for advertisements?</p>
              <img className={active === 10 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 10 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              There is no requirement that you submit content to employ our
              services. However, if you do have any content we would be
              delighted to use it.
            </p>
            <p>
              Advertisements that fit your brand can be crafted by our Account
              Manager. Our team has access to stock photography and simple
              design software. Utilizing these resources, we can develop
              interesting advertisements to engage your audience.
            </p>
          </div>
          <div
            className={styles.faqContainer}
            onClick={() => setActive(active === 11 ? 0 : 11)}
          >
            <div className={styles.question}>
              <p>
                Will you monitor the ad campaign to make sure we do not waste
                any money?
              </p>
              <img className={active === 11 && styles.rotate}
                src="https://firebasestorage.googleapis.com/v0/b/cliqtick.appspot.com/o/ststicV2%2Fdrop.png?alt=media&token=0db2857d-4f5b-4884-a17f-b53bfb970d30"
                alt="arrow"
              />
            </div>
          </div>
          <div
            className={`${styles.answer} ${
              active === 11 ? styles.scale1 : styles.scale0
            }`}
          >
            <p>
              Yes, You can count on our social media manager to be tracking your
              advertising constantly. Our team will pause ads whose performance
              is not good and modify your campaign accordingly.
            </p>
            <p>
              Additionally, your social media manager will optimize your
              campaign as time goes by. Most times, we run A/B split tests in
              your ad campaign. The process of this is to test multiple
              variations of your ads and the audiences for the ads. We are more
              likely to identify areas of efficiency if we test different
              combinations of ads.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
